### PR TITLE
Update YAML based on dagvlinders-inbo

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
@stijnvanhoey I included a conditional syntax (`if`) that is rather succinct, but still readable imo:

```
geodeticDatum:
    - if:
        - decimalLongitude:
            - populated: true
        - populated: true # Necessary, because equals does not assume this
        - equals: WGS84
     - if:
        - decimalLatitude:
            - populated: false
        - populated: false
```

**Comment by stijnvanhoey** [comment]
What if condition is dependent on the values of multiple terms? let's say: geodeticDatum is dependent ont both decimalLongitude and decimalLatitude? Would this then be solved as follows:

```
geodeticDatum:
    - if:
        - decimalLongitude:
            - populated: true
        - decimalLatitutde:
            - populated: true
        - populated: true # Necessary, because equals does not assume this
        - equals: WGS84
```
but is the relation in between two dependent terms (in this case  decimalLongitude and decimalLatitude) AND or OR?  or would this kind of multiple dependency not useful?

**Comment by peterdesmet** [comment]
Yes, what you propose would be a good syntax. And everything is combined with `AND`.

I'm not sure yet if the last two statements should be combined with `AND` or be independent. I think the latter, but that might not be what people would expect.

**Comment by stijnvanhoey** [comment]
that syntax is also ok for me to work with

**Pull request merged**
